services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
    restart: unless-stopped

  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ./n8n_data:/home/node/.n8n
    environment:
      # Disable auth for now
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_API_KEY_AUTH_ACTIVATE=false
      #- N8N_BASIC_AUTH_USER=n8n_user
      #- N8N_BASIC_AUTH_PASSWORD=n8n_password_temp
      - N8N_API_KEY=${N8N_API_KEY}
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_EDITOR_BASE_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Europe/Stockholm
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - DB_SQLITE_POOL_SIZE=5
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
    restart: unless-stopped
    depends_on:
      - ollama
      - qdrant

  n8n-setup:
    image: n8nio/n8n
    container_name: n8n_setup_cli
    
    entrypoint: ["/usr/bin/env", "sh", "-c"]
    
    command:
      - |
        # 1. Wait a couple of seconds to ensure n8n is fully booted after starting
        sleep 2 
        # 2. Execute the setup script
        /setup/n8n_setup.sh
        
    volumes:
      - ./n8n_data:/home/node/.n8n 
      - ./config:/setup
    depends_on:
      n8n:
        condition: service_started
    restart: "no"

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    restart: unless-stopped

  system-init:
    build:
      context: .
      dockerfile: Dockerfile.init
    container_name: system_init
    volumes:
      - ./scripts:/app/scripts
      - ./config:/app/config
    environment:
      - PYTHONUNBUFFERED=1 
      - N8N_API_KEY=${N8N_API_KEY} 
      - QDRANT_URL=http://qdrant:6333
      - OLLAMA_URL=http://ollama:11434
      - N8N_URL=http://n8n:5678
    depends_on:
      ollama:
        condition: service_started
      qdrant:
        condition: service_started
      n8n:
        condition: service_started
    restart: "no"

volumes:
  ollama_data:
